### ISSUE TITLE
Infinite loop (or block) in Rfc5322Parser.consume_header when no trailing newline is found.

### ISSUE THREAD

**Issue by untitaker** [niax/rust-email#12]
Let me know if you need an example.

**Comment by untitaker** [comment]
Also, I found this because my emails are not terminated with ``\r\n``, but just ``\n``.

**Comment by niax** [comment]
I mixed this up with #11 when I did the commit message, but this was fixed by @ktossell some time back but I never got round to picking out the change. There's still some fixes in his branch that I need to take a look at - I hope to get to them at the weekend. I'll roll this change into 0.0.9 along with switching to the slicing syntax.

**Comment by untitaker** [comment]
Thanks!

**Comment by untitaker** [comment]
For the record, this was fixed in 0.0.8 and works fine for me.
